### ISSUE TITLE
Is there currently a way to stop the repl after it has been started?

### ISSUE THREAD

**Issue by sa-mm** [lostfields/vscode-nodejs-repl#1]

**Comment by lostfields** [comment]
Hi
I did a quick one for 0.4.8 where it stops REPL whenever you close the active edtior it's running at.

**Comment by sabriele** [comment]
For now I open a new blank file then launch the REPL there when I want to 'pause' the REPL on my active file. REPL will switch over to the blank file and won't switch back even when you close it afterwards.

Had to do this because vscode kept prompting me to save the unsaved file I was working on every time I closed it :)

**Comment by lostfields** [comment]
Hmm, yeah, that may be a problem. 

I can look into some kind of way to stop it by introducing a new command and look into a better way to resume it.
